"""
Django settings for medicineapp project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bym2)yr&-cg&k_e9)qarqdw8rsd%6t08(i5k4qgh^fi)mzp1nq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SERVER1_URL = 'http://34.8.244.158:8080/upload/'
SERVER2_URL = 'http://34.56.24.195:8080/registro/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # Necesario para sessions
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',     # Nuevo: Requerido para autenticación
    'core',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Para manejo de sesiones
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuración de Auth0
AUTH0_DOMAIN = 'genai-8832202947885035.us.auth0.com'  # Reemplazar con tu dominio real
AUTH0_CLIENT_ID = 'MepPntI6UQ6M94bgSivMsA38fouscaGu'       # Reemplazar con tu Client ID
AUTH0_CLIENT_SECRET = 'v4nN-bJx6IW-mg_sPEm7gXsZWxBVw10PWp5b5XtaFdohtgWPdva42VVPV3DUvUHh'  # Reemplazar con tu Client Secret
AUTH0_CALLBACK_URL = 'http://localhost:8080/callback'  # Ajustar en producción
AUTH0_AUDIENCE = f'https://{AUTH0_DOMAIN}/api/v2/'
AUTH0_SCOPE = 'openid profile email'

# Configuración de autenticación
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Mantener el backend por defecto
]

# Configuración de sesiones
SESSION_COOKIE_SECURE = not DEBUG  # True en producción (requiere HTTPS)
SESSION_COOKIE_HTTPONLY = True     # Previene acceso a cookies via JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'    # Balance entre seguridad y usabilidad

# URLs de autenticación
LOGIN_URL = '/login'                # URL para redirigir usuarios no autenticados
LOGIN_REDIRECT_URL = '/'           # URL después de login exitoso
LOGOUT_REDIRECT_URL = '/'          # URL después de logout

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'medicineapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medicineapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = None

# Configuración del sitio (requerido para django.contrib.sites)
SITE_ID = 1  # Usualmente 1 para el sitio por defecto